#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division, print_function

import os
import pandas as pd

__all__ = ["format_kic"]


def format_kic(data_directory):
    fn = os.path.join(data_directory, "kic", "kic.txt")
    print("Loading KIC from txt file...")
    df = pd.read_csv(fn, sep="|")
    print("Saving to HDF5 format...")
    fn = os.path.join(data_directory, "kic", "kic.h5")
    df.to_hdf(fn, "kic", format="t")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("kepcal_data", help="the kepcal data directory")
    args = parser.parse_args()

    format_kic(args.kepcal_data)
